theme: jekyll-theme-cayman
baseurl: "alageek.com"
title: alaGeek
tagline: python, django, java, android, nodejs, javascript, erlang, türkiye, istanbul
author:
  name: Gökmen Görgen
  url: https://gokmengorgen.net
